package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,Float,BOOLean,
    If,Then,Else,While,Function,
    Return,Void,Identifier,INTeger,FLOATing,
    LeftBrace,RightBrace,LeftParen,RightParen,Comma,
    Assign,Equal,Not,NotEqual,Less,
    LessEqual,Greater,GreaterEqual,Plus,Minus,
    Or,And,Multiply,Divide,Comment
}
